<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\CategoryController::index' => function () {
    return ($this->privates['.service_locator.cxYSoue'] ?? $this->load('get_ServiceLocator_CxYSoueService.php'));
}, 'App\\Controller\\CategoryController::postCategoryAction' => function () {
    return ($this->privates['.service_locator.EbB5c0O'] ?? $this->load('get_ServiceLocator_EbB5c0OService.php'));
}, 'App\\Controller\\ProductController::deleteProductAction' => function () {
    return ($this->privates['.service_locator.KmfOZO7'] ?? $this->load('get_ServiceLocator_KmfOZO7Service.php'));
}, 'App\\Controller\\ProductController::getProductAction' => function () {
    return ($this->privates['.service_locator.4ezSskK'] ?? $this->load('get_ServiceLocator_4ezSskKService.php'));
}, 'App\\Controller\\ProductController::index' => function () {
    return ($this->privates['.service_locator.4ezSskK'] ?? $this->load('get_ServiceLocator_4ezSskKService.php'));
}, 'App\\Controller\\ProductController::postProductAction' => function () {
    return ($this->privates['.service_locator.KmfOZO7'] ?? $this->load('get_ServiceLocator_KmfOZO7Service.php'));
}, 'App\\Controller\\ProductController::updateProductAction' => function () {
    return ($this->privates['.service_locator.KmfOZO7'] ?? $this->load('get_ServiceLocator_KmfOZO7Service.php'));
}, 'App\\Controller\\CategoryController:index' => function () {
    return ($this->privates['.service_locator.cxYSoue'] ?? $this->load('get_ServiceLocator_CxYSoueService.php'));
}, 'App\\Controller\\CategoryController:postCategoryAction' => function () {
    return ($this->privates['.service_locator.EbB5c0O'] ?? $this->load('get_ServiceLocator_EbB5c0OService.php'));
}, 'App\\Controller\\ProductController:deleteProductAction' => function () {
    return ($this->privates['.service_locator.KmfOZO7'] ?? $this->load('get_ServiceLocator_KmfOZO7Service.php'));
}, 'App\\Controller\\ProductController:getProductAction' => function () {
    return ($this->privates['.service_locator.4ezSskK'] ?? $this->load('get_ServiceLocator_4ezSskKService.php'));
}, 'App\\Controller\\ProductController:index' => function () {
    return ($this->privates['.service_locator.4ezSskK'] ?? $this->load('get_ServiceLocator_4ezSskKService.php'));
}, 'App\\Controller\\ProductController:postProductAction' => function () {
    return ($this->privates['.service_locator.KmfOZO7'] ?? $this->load('get_ServiceLocator_KmfOZO7Service.php'));
}, 'App\\Controller\\ProductController:updateProductAction' => function () {
    return ($this->privates['.service_locator.KmfOZO7'] ?? $this->load('get_ServiceLocator_KmfOZO7Service.php'));
})));
