<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cxYSoue' shared service.

return $this->privates['.service_locator.cxYSoue'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('categoryRepository' => function (): \App\Repository\CategoryRepository {
    return ($this->privates['App\Repository\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php'));
}));
