<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK3yEhxl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK3yEhxl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK3yEhxl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK3yEhxl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerK3yEhxl\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'K3yEhxl',
    'container.build_id' => 'ab989614',
    'container.build_time' => 1540934977,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK3yEhxl');
