<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5DP6RB\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5DP6RB/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY5DP6RB.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY5DP6RB\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerY5DP6RB\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Y5DP6RB',
    'container.build_id' => '30ed1671',
    'container.build_time' => 1540927685,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5DP6RB');
